[package]
name = "ragdoll"
version = "0.1.0"
authors = ["solarsail"]

[dependencies]
piston_window = "0.50.0"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/PistonDevelopers/sdl2_window"
