refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h([{l}])}[{M}] {m}{n}"
  file:
    kind: file
    path: "log/ragdoll.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h([{l}])}[{M}] {m}{n}"
root:
  level: debug
  appenders:
    - stdout
loggers:
  ragdoll:
    level: debug
    appenders:
      - file